# Generated by Django 3.1.2 on 2020-11-06 15:23

from django.db import migrations, models
import main.custom_validators.custom_username_validators
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201104_1948'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[main.custom_validators.custom_username_validators.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
